# Generated by Django 6.0 on 2025-12-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
