# Generated by Django 6.0 on 2025-12-15 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobposting_salary_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='employment_means',
            field=models.CharField(choices=[('RE', 'Remote'), ('ON', 'On-site'), ('HY', 'Hybrid')], default='ON', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('AP', 'Applied'), ('IN', 'Interview'), ('OF', 'Offer'), ('RE', 'Rejection')], default='AP', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'job')},
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField()),
                ('interviewer', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('means_of_interview', models.CharField(choices=[('PH', 'Phone'), ('VI', 'Video Call'), ('IN', 'In-Person')], default='PH', max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.application')),
            ],
        ),
    ]
