# Generated by Django 6.0 on 2025-12-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
    ]
