# Generated by Django 6.0 on 2025-12-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_interview_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('AP', 'Applied'), ('IN', 'Interview'), ('OF', 'Offer'), ('RE', 'Rejection')], default='DR', max_length=2),
        ),
        migrations.AlterField(
            model_name='interview',
            name='means_of_interview',
            field=models.CharField(choices=[('PH', 'Phone'), ('VI', 'Video Call'), ('IN', 'In-Person')], default='PH', max_length=2),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='employment_means',
            field=models.CharField(choices=[('RE', 'Remote'), ('ON', 'On-site'), ('HY', 'Hybrid')], default='ON', max_length=2),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('IN', 'Internship')], default='FT', max_length=2),
        ),
    ]
